# ----
# Site

title: En Renare Vardag AB
url: "https://enrenarevardag.se"
baseurl:
google_analytics_key:
# google_maps_javascript_api_key:
# disqus_shortname:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: 'Din städfirma i Stockholm - Vår service betyder omtanke'
author:
  name: En Renare Vardag AB
  email: info@enrenarevardag.se
#  twitter: # twitter username without the @ symbol
social:
  name: En Renare Vardag AB
  links:
    - https://www.facebook.com/enrenarevardagAB/
    - https://www.linkedin.com/company/en-renare-vardag-i-stockholm-ab
    - https://www.instagram.com/enrenarevardag/

# -----
# Build

timezone: Etc/UTC

permalink: /:categories/:title/

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate-v2

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

collections:
  foretag:
    output: true
    permalink: /foretag/:name/
    layout: generic
  privat:
    output: true
    permalink: /privat/:name/
    layout: generic


defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      type: "posts"
    values:
      layout: "post"

sass:
    sass_dir: /assets/sass/
